name: CI

on:
  push:
  pull_request:
    branches:
      - 'main'
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Setup virtualenv
        uses: syphar/restore-virtualenv@v1
        id: lint-venv-cache

      - name: Restore pip cache download 
        uses: syphar/restore-pip-download-cache@v1
        if: steps.lint-venv-cache.outputs.cache-hit != 'true'

      - name: Install requirements
        if: steps.lint-venv-cache.outputs.cache-hit != 'true'
        run: |
          pip install -U -r requirements.txt
          pip install -U -r requirements-dev.txt

      - name: Execute multilint scripts
        run: |
          python3 ci/multilint.py -si -sv

      - name: Test
        run: |
          python3 -m pytest -v --cov=nmanga --cov-report=xml --cov-report=term-missing tests/

      - name: Code Coverage Report
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: coverage.xml
          badge: true
          fail_below_min: false
          format: markdown
          hide_branch_rate: false
          hide_complexity: true
          indicators: true
          output: both
          thresholds: '40 75'

      - name: Add Coverage PR Comment
        uses: marocchino/sticky-pull-request-comment@v2
        if: github.event_name == 'pull_request'
        with:
          recreate: true
          path: code-coverage-results.md
